include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.2

LUCI_TITLE:=LuCI Support for nikkix
LUCI_DEPENDS:=+luci-base +nikkix

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
